### ISSUE TITLE
Add Pre-Steampipe Source mods.

### ISSUE THREAD

**Issue by malortie** [HL2-Mods-Legacy-Project/hl2-legacy-main#90]
# Mods to add

## Singleplayer

- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#3
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#4
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#44
- [ ] #92
- [ ] ASDA ?
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#18
- [ ] #93
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#5
- [ ] Bloodstone: The Journey Home ?
- [x] #94
- [ ] #95
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#86
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#19
- [ ] #96
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#20
- [x] #97
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#85
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#6
- [ ] #98
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#45
- [ ] CSS Sci-Fi 3 ?
- [ ] Cyberscape ?
- [ ] #99
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#46
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#47
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#21
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#48
- [x] #100
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#84
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#65
- [ ] Depot ?
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#66
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#13
- [ ] Escape ExMo ?
- [ ] #101
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#7
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#49
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#14
- [ ] #102
- [ ] #103
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#50
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#15
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#16
- [ ] Hard Escape ?
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#69
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#8
- [ ] #104
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#9
- [ ] #105
- [x] #106
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#70
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#83
- [ ] #107
- [ ] #108
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#23
- [ ] #142
- [x] #109
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#24
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#25
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#10
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#52
- [ ] Mission to Mars ?
- [ ] #110
- [ ] #111
- [ ] #112
- [ ] Nightmare House ?
- [ ] #113
- [ ] #114
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#141
- [ ] #115
- [ ] Opposing Force: Ravenholm ?
- [x] #116
- [ ] #117
- [ ] #118
- [ ] #119
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#81
- [ ] #120
- [ ] #121
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#82
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#11
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#26
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#54
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#12
- [ ] #122
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#51
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#55
- [ ] Samurai Legends ?
- [x] ~~#123~~ (invalid)
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#72
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#27
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#28
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#17
- [ ] #124
- [ ] #125
- [ ] Sity ?
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#56
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#57
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#58
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#59
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#60
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#61
- [ ] #126
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#73
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#62
- [ ] #127
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#75
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#80
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#77
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#30
- [x] #128
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#29
- [ ] #129
- [ ] #130
- [ ] #131
- [ ] #132
- [ ] The Sewer ?
- [ ] #133
- [ ] #134
- [ ] #135
- [ ] Unexpected Conclusion ?
- [ ] Union ?
- [ ] Uzvara ?
- [ ] HL2-Mods-Legacy-Project/hl2-legacy-main#88
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#78
- [ ] #136
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#31
- [ ] Zombie Escape ?
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#32

## Multiplayer

- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#64
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#2
- [x] #139
- [ ] Follow Freeman Coop ?
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#22
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#67
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#68
- [ ] #137
- [ ] HL2DM Pro ?
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#71
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#53
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#79
- [x] #138
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#63
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#74
- [ ] Synergy ?
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#89
- [x] HL2-Mods-Legacy-Project/hl2-legacy-main#76
- [ ] Tim Coop ?
- [ ] Toybox Heroes ?
